### ISSUE TITLE
how to find out what test failed?

### ISSUE THREAD

**Issue by jwaldmann** [rudymatela/leancheck#13]
I am making experimental changes to  leancheck itself. I am using test/*.hs for testing my changes. I want to know which of the properties fail, but currently `tests :: [Bool]` . Should probably use 
some testing framework. 

But then, we get circular dependencies at the package level?

* leancheck (for running tests only) would depend on (e.g.,) hspec-leancheck
* hspec-leancheck (implementation) depends on leancheck

We could merge hspec-leancheck with leancheck (just to break this loop)
but then leancheck depends on hspec and this pulls in a heap of transitive dependencies, and then we're no longer "lean".

**Comment by jwaldmann** [comment]
OK, I think current output
```
Failed tests:[31,34]
```
is enough - given the complications of using a framework, listed above.

**Comment by rudymatela** [comment]
:smile:

@jwaldmann I know you closed this issue yourself, but I just wanted to leave a couple comments for future reference.

> But then, we get circular dependencies at the package level?

I haven't tested this to confirm, but I don't think we would get circular dependencies actually.  `lenacheck` itself wouln't depend on `hspec-leancheck`, only it's test suites.  So I _think_ cabal may be able to handle that.

Nevertheless, your further comment captures what I had in my mind:

> but then leancheck depends on hspec and this pulls in a heap of transitive dependencies, and then we're no longer "lean".

So yes, I made a compromise by having a "lightweight" test framework for LeanCheck that reports the quite terse: `Failed tests:[31,34]`.
