### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by bfrk** [rudymatela/leancheck#17]
I am testing with a large number of tests and noticed that this seems to use up more and more memory. For instance with the example from Test.LeanCheck with a few more tests:

```
Data.List Prelude Test.LeanCheck> holds 10000000 $ \xs -> length (sort xs) == length (xs::[Int])
zsh: segmentation fault  ghci
```

With a compiled program this eats up all the memory on my machine until it starts thrashing (ghc-8.2.2).

**Comment by bfrk** [comment]
Sorry, this is a duplicate, see https://github.com/rudymatela/leancheck/issues/15

**Comment by rudymatela** [comment]
:-)
