### ISSUE TITLE
Please add Changelog

### ISSUE THREAD

**Issue by jwaldmann** [rudymatela/leancheck#8]
Please add Changelog information in some canonical place 

(I think changelog.md will be shown automatically on hackage)

**Comment by rudymatela** [comment]
Fair enough.  I'll add a `changelog.md` in an upcoming release.

For now, to see what changed between versions you can look at the release tags:

https://github.com/rudymatela/leancheck/releases

There is a small changelog attached to each entry (on GitHub you have to click on `...`).

**Comment by rudymatela** [comment]
@jwaldmann Thanks for the suggestion.  I have added a [changelog] and published a new version of [LeanCheck]: [v0.7.7].

[changelog]: https://hackage.haskell.org/package/leancheck/changelog
[LeanCheck]: https://hackage.haskell.org/package/leancheck
[v0.7.7]: https://hackage.haskell.org/package/leancheck-0.7.7
